Change database password on Debian without resorting to dpkg.  #1117

diff --git a/pscheduler-server/pscheduler-server/unibuild-packaging/deb/postinst b/pscheduler-server/pscheduler-server/unibuild-packaging/deb/postinst
--- a/pscheduler-server/pscheduler-server/unibuild-packaging/deb/postinst
+++ b/pscheduler-server/pscheduler-server/unibuild-packaging/deb/postinst
@@ -109,31 +109,17 @@ case "$1" in
         if [ -f /usr/share/dbconfig-common/dpkg/postinst.pgsql ]; then
             . /usr/share/dbconfig-common/dpkg/postinst.pgsql
             rm -f /var/cache/dbconfig-common/backups/pscheduler-server_*
-            db_set pscheduler-server/upgrade-backup false
-            dbc_go pscheduler-server $@
+
+	    # Nonzero return conveys status and not errors.  Can't
+	    # seem to find solid docs on that, but this does seem to
+	    # work.  --MF
+            db_set pscheduler-server/upgrade-backup false || true
+            dbc_go pscheduler-server $@ || true
         fi
 
         # release debconf descriptor
         db_stop
 
-        # update database passwords
-        if [ -r /etc/dbconfig-common/pscheduler-server.conf ]; then
-            (
-                . /etc/dbconfig-common/pscheduler-server.conf
-
-                echo "dbname=$dbc_dbname user=$dbc_dbuser password=$dbc_dbpass" \
-                    > /etc/pscheduler/database/database-dsn
-                echo "$dbc_dbpass" > /etc/pscheduler/database/database-password
-                echo "*:*:$dbc_dbname:$dbc_dbuser:$dbc_dbpass" > /etc/pscheduler/database/pgpassfile
-
-                chmod 600 /etc/pscheduler/database/database-dsn \
-                          /etc/pscheduler/database/database-password \
-                          /etc/pscheduler/database/pgpassfile
-                chown pscheduler:root /etc/pscheduler/database/database-dsn \
-                                      /etc/pscheduler/database/database-password \
-                                      /etc/pscheduler/database/pgpassfile
-            )
-        fi
 	pscheduler internal db-change-password
 
         # handle large number of pscheduler connections
